version: '2'

services:
    base:
        build: ./
        image: "${REGISTRY_URL}hit-maker${SERVICE_VERSION}"

    run_unit_tests:
        extends:
            service: base
        command: bash -c "./scripts/run_unit_tests.sh"
        volumes:
            - ./:/source/hit-maker

    app:
        extends:
            service: base
        command: bash -c "./scripts/run_service.sh"
        volumes:
            - ./:/source/hit-maker